<a href="https://colab.research.google.com/github/LUCASDNORONHA/Clusters-KMeans/blob/main/Cluster_KMeans.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Agrupamento

# K-means

In [56]:
!pip install plotly --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 82.1 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.15.0
    Uninstalling plotly-5.15.0:
      Successfully uninstalled plotly-5.15.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
lida 0.0.10 requires fastapi, which is not installed.
lida 0.0.10 requires kaleido, which is not installed.
lida 0.0.10 requires python-multipart, which is not installed.
lida 0.0.10 requires uvicorn, which is not installed.


In [57]:
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px
from sklearn.preprocessing import StandardScaler

## Base Idade e Salário

In [58]:
from sklearn.cluster import KMeans

X = [20, 27, 21, 37, 46, 55, 47, 52, 32, 39, 41, 39, 48, 48]
y = [1000, 1200, 2900, 1850, 900, 2000, 2100, 3000, 5900, 4100, 5100, 7000, 5000, 6500]

In [59]:
grafico = px.scatter(x=X, y=y)
grafico.update_layout(title_text='Idade x Salário')
grafico.update_xaxes(title_text='Idade')
grafico.update_yaxes(title_text='Salário')
grafico.update_traces(hovertemplate='Valor: %{y}')

grafico.show()

In [60]:
data = np.array([[20,1000], [27,1200], [21,2900], [37, 1850], [46,900],
                 [53,950], [55,2000], [47, 2100], [52,3000], [32,5900],
                 [39,4100], [41,5100], [39,7000], [48,5000], [48,6500]])

In [61]:
data

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [62]:
scaler = StandardScaler()
data = scaler.fit_transform(data)

In [63]:
data

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [64]:
model_kmeans = KMeans(n_clusters=3)
model_kmeans.fit(data)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=3)

In [65]:
centroides = model_kmeans.cluster_centers_
centroides

array([[ 0.73953003, -0.72661025],
       [ 0.07703438,  1.11413572],
       [-1.63312883, -0.77505093]])

In [66]:
scaler.inverse_transform(model_kmeans.cluster_centers_)

array([[  48.33333333, 1800.        ],
       [  41.16666667, 5600.        ],
       [  22.66666667, 1700.        ]])

In [67]:
rotulos = model_kmeans.labels_
rotulos

array([2, 2, 2, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32)

In [68]:
grafico1 = px.scatter(x=data[:,0], y=data[:,1], color=rotulos)
grafico2 = px.scatter(x= centroides[:,0], y=centroides[:,1], size=[12,12,12])
grafico3 = go.Figure(data= grafico1.data + grafico2.data)
grafico3.update_layout(title_text='Clusters')
grafico3.show()

# Dados Randômicos

In [69]:
from sklearn.datasets import make_blobs

In [70]:
X_random, y_random,  = make_blobs(n_samples=200, centers=5, random_state=0)

In [71]:
X_random

array([[ 1.36069966,  0.74802912],
       [-3.27894024,  9.89995288],
       [ 0.58894326,  4.00148458],
       [-0.97373942,  6.94454493],
       [ 2.43169305, -0.20173713],
       [ 0.62835793,  4.4601363 ],
       [-2.16434104,  2.52061045],
       [-0.65392827,  4.76656958],
       [ 0.73240494,  2.87562511],
       [ 1.956815  ,  0.23418537],
       [ 2.11567076,  3.06896151],
       [ 3.18190344, -0.18226785],
       [ 7.01769098, -3.35367647],
       [-2.34026827,  1.45145793],
       [ 0.30380963,  3.94423417],
       [ 0.829832  ,  1.74202664],
       [-3.06770103,  2.98114426],
       [-1.36641982,  7.15528181],
       [-1.10630261,  7.5161316 ],
       [ 2.41163392,  1.60423683],
       [-2.37508158,  7.10478226],
       [-2.47135027,  2.50783257],
       [ 2.47034915,  4.09862906],
       [-1.63313558,  7.9298116 ],
       [ 8.58924431, -0.67161883],
       [ 3.92282648,  1.80370832],
       [-1.38420548,  8.97235138],
       [ 1.05566092,  6.77544419],
       [ 9.08260172,

In [72]:
y_random

array([1, 3, 0, 3, 1, 0, 2, 0, 2, 1, 0, 1, 4, 2, 0, 1, 2, 3, 3, 1, 3, 2,
       0, 3, 4, 1, 3, 3, 4, 3, 1, 2, 0, 0, 2, 0, 4, 3, 1, 0, 2, 0, 0, 1,
       4, 4, 4, 1, 1, 3, 0, 1, 3, 1, 4, 4, 2, 3, 4, 1, 4, 4, 2, 0, 2, 4,
       0, 1, 1, 4, 4, 1, 4, 0, 0, 4, 2, 2, 2, 1, 3, 3, 1, 1, 3, 3, 0, 0,
       4, 4, 3, 4, 3, 3, 0, 0, 1, 2, 4, 0, 0, 2, 4, 1, 1, 4, 4, 3, 0, 2,
       1, 0, 4, 3, 2, 1, 2, 0, 2, 2, 4, 0, 4, 2, 0, 2, 0, 3, 0, 2, 2, 0,
       3, 1, 3, 4, 0, 2, 4, 4, 1, 4, 2, 2, 3, 1, 1, 3, 1, 0, 2, 3, 4, 4,
       4, 0, 3, 2, 0, 4, 3, 3, 2, 3, 1, 2, 3, 3, 4, 0, 2, 2, 2, 1, 0, 3,
       4, 3, 3, 1, 1, 2, 0, 2, 2, 0, 2, 0, 3, 3, 4, 1, 1, 1, 1, 1, 4, 4,
       2, 3])

In [73]:
grafico = px.scatter(x=X_random[:,0], y= X_random[:,1])
grafico.show()

In [74]:
model_kmeans = KMeans(n_clusters=5)
model_kmeans.fit(X_random)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning:

The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning



KMeans(n_clusters=5)

In [75]:
rotulos =  model_kmeans.predict(X_random)
rotulos

array([3, 0, 4, 0, 3, 4, 2, 4, 4, 3, 3, 3, 1, 2, 4, 3, 2, 0, 0, 3, 0, 2,
       4, 0, 1, 3, 0, 4, 1, 0, 3, 2, 2, 4, 2, 4, 1, 0, 3, 4, 2, 4, 4, 3,
       1, 1, 1, 3, 3, 0, 4, 3, 0, 3, 1, 1, 2, 0, 1, 3, 1, 1, 2, 4, 2, 1,
       2, 3, 3, 1, 1, 3, 1, 4, 0, 1, 4, 2, 2, 3, 0, 4, 3, 3, 0, 0, 4, 4,
       1, 1, 0, 1, 0, 0, 4, 4, 3, 2, 1, 4, 4, 2, 1, 3, 3, 1, 1, 0, 4, 2,
       3, 4, 1, 0, 2, 3, 2, 2, 2, 2, 1, 4, 1, 4, 4, 2, 4, 0, 3, 2, 2, 4,
       0, 3, 0, 1, 4, 2, 1, 1, 3, 1, 2, 2, 0, 3, 3, 0, 3, 4, 2, 0, 1, 1,
       1, 2, 0, 2, 3, 1, 0, 0, 2, 0, 3, 2, 0, 0, 1, 4, 2, 2, 3, 3, 4, 0,
       1, 0, 0, 3, 3, 2, 4, 2, 2, 4, 2, 4, 0, 0, 1, 4, 3, 3, 3, 3, 1, 1,
       2, 0], dtype=int32)

In [76]:
centroides = model_kmeans.cluster_centers_
centroides

array([[-1.5489702 ,  8.00822173],
       [ 9.14794457, -2.61667701],
       [-1.61910687,  2.7281839 ],
       [ 2.04809825,  1.38768696],
       [ 0.83004062,  4.4315902 ]])

In [77]:
grafico1 = px.scatter(x = X_random[:,0], y = X_random[:,1], color = rotulos)
grafico2 = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [5, 5, 5, 5, 5])
grafico3 = go.Figure(data = grafico1.data + grafico2.data)
grafico3.show()